title = "Adonis"
gitRepoUrl = "https://github.com/Sceleratis/Adonis_2.0"

[home]
enabled = true
includeReadme = false

[docusaurus]
tagline = "Roblox Server Administration System"
favicon = "/favicon.png"